import { tutorialPt } from "./tutorial.js";
import { expansionPt } from "./expansion.js";
import { coreEn, tutorialEn, expansionEn, noblePhantasmEn } from "./en.js";
export type Locale = "pt-BR" | "en-US";
const pt: Record<string, string> = {
  ...tutorialPt,
  ...expansionPt,
  manaEfficiency: "Eficiência de cura",
  mystery: "Mistério",
  limits: "Limites por Agent / partida",
  maxRequests: "Máximo de chamadas",
  maxTokens: "Orçamento de tokens",
  maxOutputTokens: "Tokens por resposta",
  timeoutMs: "Tempo por decisão (ms)",
  retries: "Retries",
  maxToolCalls: "Tools por decisão",
  maxCost: "Limite de custo (opcional)",
  inputPrice: "Preço por milhão de tokens de entrada",
  outputPrice: "Preço por milhão de tokens de saída",
  title: "HOLY GRAIL WAR",
  subtitle: "Sete classes. Um desejo. Nenhuma certeza.",
  eyebrow: "CRÔNICAS DO GRAAL",
  play: "Iniciar ritual",
  lobby: "Preparar a guerra",
  lobbyDescription:
    "Escolha os participantes. O destino de cada Servant será decidido pelo ritual.",
  war: "Guerra",
  archive: "Arquivo",
  settings: "Configurações",
  back: "Voltar",
  close: "Fechar",
  save: "Salvar partida",
  saved: "Partida salva",
  resume: "Continuar",
  seed: "Seed da guerra",
  locations: "Locais",
  players: "Masters",
  human: "Humano",
  bot: "Bot",
  agent: "Agent",
  name: "Nome",
  profile: "Perfil",
  provider: "Provider",
  model: "Modelo",
  baseUrl: "URL base",
  apiKey: "Chave de API",
  connect: "Salvar conexão",
  test: "Testar conexão",
  connected: "Conexão validada",
  deleteProvider: "Apagar",
  deleteProviderConfirm: "Apagar a conexão",
  providerDeleted: "Conexão apagada",
  providers: "Conexões de Agents",
  providerHelp:
    "Opcional. Human + Bots funciona sem conexão. Credenciais ficam apenas na memória do servidor.",
  providerId: "Identificador",
  providerMissing: "Sem provider — Bot fallback",
  locale: "Idioma",
  motion: "Reduzir animações",
  noSaves: "Nenhuma crônica salva ainda.",
  loading: "Carregando…",
  busy: "Os outros Masters estão decidindo…",
  error: "Não foi possível concluir a ação.",
  confirm: "Confirmar decisão",
  advance: "Avançar fase",
  summon: "Concluir invocação",
  ritual: "O chamado",
  ritualDescription:
    "O Graal escuta suas intenções. Nenhuma escolha garante quem responderá.",
  manaWarning:
    "Mana oferecida é consumida permanentemente. Uma invocação mais rara deixa menos recursos para cura.",
  desiredTrait: "Que tipo de Servant você procura?",
  grailWish: "O que você deseja do Graal?",
  alignment: "Qual é seu alinhamento?",
  catalyst: "Qual catalisador usará?",
  classFocus: "Qual classe deseja atrair?",
  manaOffering: "Quanto de Mana oferecerá?",
  day: "Dia",
  mana: "Mana",
  hp: "Vitalidade",
  np: "Noble Phantasm",
  unknown: "Identidade desconhecida",
  identity: "Identidade",
  eliminated: "Eliminado",
  victory: "A guerra terminou",
  draw: "O Graal permanece sem dono",
  winner: "Vencedor",
  results: "Resultados",
  replay: "Rever a crônica",
  replayStep: "Decisão",
  journal: "Crônica da guerra",
  noEvents: "O silêncio precede o ritual.",
  locationTitle: "Escolha seu destino",
  locationDescription:
    "Seu destino será selado antes da ação diurna e revelado ao anoitecer.",
  dayTitle: "Uma decisão antes da noite",
  dayDescription: "Ações diurnas são secretas e resolvidas simultaneamente.",
  combatTitle: "O encontro",
  combatDescription:
    "Escolha um ataque contra cada rival. Todos os ataques acontecerão, mesmo que seu Servant seja derrotado.",
  noBattle: "Nenhum adversário neste local.",
  spectating: "Seu Master foi eliminado. Avance para acompanhar o desfecho.",
  npUse: "Liberar Noble Phantasm",
  npHelp:
    "Atinge todos os rivais, consome 5 cargas e revela sua identidade aos presentes.",
  target: "Alvo",
  amount: "Mana a transferir",
  locked: "Destino selado",
  ownServant: "Seu Servant",
  rivals: "Masters rivais",
  city: "A cidade adormecida",
  condition: "Condição",
  telemetry: "Telemetria",
  damage: "Dano causado",
  requests: "Decisões de Agent",
  fallbacks: "Fallbacks",
  offline: "JOGÁVEL OFFLINE",
  principle: "Controllers decide. Game Engine resolves.",
  about: "Uma guerra de informação, destinos ocultos e combates simultâneos.",
  setup: "Configurar partida",
  connectionId: "ex.: local-model",
  modelPlaceholder: "Nome do modelo instalado",
  namePlaceholder: "Nome do Master",
  download: "Exportar replay",
  summoningCost: "Custo de Mana",
  settingsSaved: "Configurações salvas",
  classes: "Classes",
  roster: "Espíritos heroicos",
  prepared: "Terreno preparado",
  ritualOdds:
    "Mais Mana aumenta a chance de raridade. Classe, catalisador e compatibilidade influenciam os pesos.",
  SUMMONING: "Invocação",
  LOCATION: "Destino",
  DAY_ACTION: "Ação diurna",
  COMBAT: "Noite",
  FINISHED: "Desfecho",
  Balanced: "Equilibrado",
  Aggressive: "Agressivo",
  Cautious: "Cauteloso",
  Investigator: "Investigador",
  Survivalist: "Sobrevivente",
  INVESTIGATE_SERVANT: "Investigar Servant",
  INVESTIGATE_MASTER: "Investigar Master",
  TRANSFER_MANA: "Transferir Mana",
  PREPARE_TERRAIN: "Preparar terreno",
  HIDE: "Ocultar-se",
  USE_LEYLINE: "Usar linha ley",
  "help.INVESTIGATE_SERVANT":
    "Avance na identidade de um rival; o Mistério dele reduz o ganho. Com 100%, revele o Servo e cause 25% mais dano contra ele. Ocultar-se bloqueia a investigação.",
  "help.INVESTIGATE_MASTER":
    "Descubra dois destinos possíveis do alvo; exatamente um será verdadeiro.",
  "help.TRANSFER_MANA":
    "Consuma Mana para restaurar vitalidade conforme a eficiência do Servant.",
  "help.PREPARE_TERRAIN":
    "+25% de dano no local escolhido, somente nesta noite.",
  "help.HIDE": "Bloqueie investigações contra você neste dia.",
  "help.USE_LEYLINE": "+1 carga de Noble Phantasm, até 5.",
  POWER: "Poder",
  LOYALTY: "Lealdade",
  CUNNING: "Astúcia",
  KNOWLEDGE: "Conhecimento",
  CHAOS: "Caos",
  RESILIENCE: "Resiliência",
  ANY: "Qualquer espírito",
  PROTECTION: "Proteção",
  REDEMPTION: "Redenção",
  FREEDOM: "Liberdade",
  RECOGNITION: "Reconhecimento",
  CHANGE_THE_WORLD: "Mudar o mundo",
  NO_WISH: "Sem desejo",
  LAWFUL_GOOD: "Leal e bom",
  LAWFUL_NEUTRAL: "Leal e neutro",
  LAWFUL_EVIL: "Leal e maligno",
  NEUTRAL_GOOD: "Neutro e bom",
  TRUE_NEUTRAL: "Neutro verdadeiro",
  NEUTRAL_EVIL: "Neutro e maligno",
  CHAOTIC_GOOD: "Caótico e bom",
  CHAOTIC_NEUTRAL: "Caótico e neutro",
  CHAOTIC_EVIL: "Caótico e maligno",
  ROYAL_RELIC: "Relíquia real",
  ANCIENT_WEAPON: "Fragmento de arma antiga",
  SACRED_RELIC: "Relíquia sagrada",
  MYSTIC_ARTIFACT: "Artefato místico",
  WARRIOR_RELIC: "Relíquia de guerreiro",
  OLD_MANUSCRIPT: "Manuscrito antigo",
  CRIMINAL_RELIC: "Relíquia de criminoso",
  NONE: "Sem preferência",
  LOW: "Baixa · 10 Mana",
  MEDIUM: "Média · 25 Mana",
  HIGH: "Alta · 45 Mana",
  EXTREME: "Extrema · 65 Mana",
  SABER: "Saber",
  ARCHER: "Archer",
  LANCER: "Lancer",
  RIDER: "Rider",
  CASTER: "Caster",
  ASSASSIN: "Assassin",
  BERSERKER: "Berserker",
  BUSTER: "Buster",
  ARTS: "Arts",
  QUICK: "Quick",
  HEALTHY: "Saudável",
  WOUNDED: "Ferido",
  CRITICAL: "Crítico",
  DEFEATED: "Derrotado",
  UNKNOWN: "Desconhecida",
  "location-1": "Porto das Cinzas",
  "location-2": "Templo da Lua",
  "location-3": "Jardim Esquecido",
  "location-4": "Torre do Relógio",
  "location-5": "Velha Estação",
  "location-6": "Ponte Velada",
  "location-7": "Biblioteca",
  "location-8": "Observatório",
  SUMMONED: "Um espírito respondeu ao chamado",
  DAY_STARTED: "Um novo dia começa",
  NIGHT_STARTED: "Os destinos são revelados",
  MANA_SPENT: "Mana consumida",
  HEALED: "Vitalidade restaurada",
  IDENTITY_GAINED: "Progresso de identidade",
  IDENTITY_DISCOVERED: "Nome verdadeiro descoberto",
  INVESTIGATION_BLOCKED: "Investigação bloqueada",
  LOCATION_CLUE: "Destinos possíveis",
  LOCATION_REVEALED: "Destino revelado",
  DAMAGE_RESOLVED: "Ataque resolvido",
  NP_USED: "Noble Phantasm liberado",
  ELIMINATION_CREDIT: "Contribuição para eliminação",
  PLAYER_ELIMINATED: "Master eliminado",
  MATCH_FINISHED: "A guerra chegou ao fim",
  INVALID_INPUT: "Confira os campos informados.",
  INSUFFICIENT_MANA: "Mana insuficiente.",
  MATCH_BUSY: "Aguarde a decisão dos outros Masters.",
  SESSION_REQUIRED: "Recarregue a página para abrir a sessão local.",
  REQUEST_FAILED:
    "A operação falhou. Confira a configuração e tente novamente.",
  REPLAY_AVAILABLE_AFTER_MATCH: "Replay disponível após o fim da partida.",
  INVALID_PROVIDER_URL: "A URL do provider não é válida.",
  HTTPS_REQUIRED_FOR_REMOTE_PROVIDER: "Use HTTPS para providers remotos.",
  PROVIDER_HTTP_401: "Credencial recusada pelo provider.",
  PROVIDER_HTTP_404: "Endpoint ou modelo não encontrado.",
  PROVIDER_UNAVAILABLE: "Provider indisponível; o Bot assume.",
  BROWSER_STORAGE_FULL:
    "O navegador não tem espaço para salvar. Libere dados do site e tente novamente.",
  SAVE_NOT_FOUND: "Save não encontrado.",
  PROVIDER_NOT_FOUND: "Conexão não encontrada. Salve-a novamente.",
  PROVIDER_HTTP_400:
    "O serviço recusou a requisição. Confira o nome do modelo.",
  PROVIDER_HTTP_429: "Limite de uso do serviço atingido. Tente mais tarde.",
  PROVIDER_NO_CREDIT:
    "Conexão estabelecida, mas a conta do serviço está sem saldo ou créditos.",
  PROVIDER_INVALID_KEY: "A API key foi recusada. Confira a chave informada.",
  PROVIDER_MODEL_NOT_FOUND:
    "O serviço não encontrou esse modelo. Confira o nome exato.",
  PROVIDER_RATE_LIMIT:
    "Muitas requisições ao serviço em pouco tempo. Tente mais tarde.",
  PROVIDER_TIMEOUT: "O modelo demorou demais para responder.",
  PROVIDER_UNREACHABLE:
    "Não foi possível conectar ao serviço. Confira a URL e se o Ollama está aberto.",
  PROVIDER_INVALID_RESPONSE: "O serviço respondeu num formato inesperado.",
  PROVIDER_INVALID_JSON: "O modelo respondeu, mas não em JSON válido.",
  PROVIDER_OUTPUT_TRUNCATED:
    "A resposta foi cortada. Aumente o limite de tokens por resposta.",
  EMPTY_PROVIDER_RESPONSE: "O modelo devolveu uma resposta vazia.",
};
const en: Record<string, string> = {
  ...coreEn,
  ...tutorialEn,
  ...expansionEn,
  ...noblePhantasmEn,
  title: "HOLY GRAIL WAR",
  subtitle: "Seven classes. One wish. No certainty.",
  eyebrow: "GRAIL CHRONICLES",
  play: "Begin ritual",
  lobby: "Prepare the war",
  lobbyDescription:
    "Choose the participants. The ritual will decide each Servant.",
  war: "War",
  archive: "Archive",
  settings: "Settings",
  back: "Back",
  close: "Close",
  save: "Save match",
  saved: "Match saved",
  resume: "Resume",
  seed: "War seed",
  locations: "Locations",
  players: "Masters",
  human: "Human",
  bot: "Bot",
  agent: "Agent",
  name: "Name",
  profile: "Profile",
  provider: "Provider",
  model: "Model",
  baseUrl: "Base URL",
  apiKey: "API key",
  connect: "Save connection",
  test: "Test connection",
  connected: "Connection verified",
  deleteProvider: "Delete",
  deleteProviderConfirm: "Delete connection",
  providerDeleted: "Connection deleted",
  providers: "Agent connections",
  providerHelp:
    "Optional. Human + Bots runs offline. Credentials remain in server memory.",
  locale: "Language",
  motion: "Reduce motion",
  noSaves: "No saved chronicles yet.",
  loading: "Loading…",
  busy: "The other Masters are deciding…",
  confirm: "Confirm decision",
  advance: "Advance phase",
  summon: "Complete summoning",
  ritual: "The calling",
  day: "Day",
  mana: "Mana",
  hp: "Vitality",
  np: "Noble Phantasm",
  unknown: "Unknown identity",
  identity: "Identity",
  eliminated: "Eliminated",
  victory: "The war has ended",
  draw: "The Grail has no owner",
  winner: "Winner",
  results: "Results",
  replay: "Review chronicle",
  journal: "War chronicle",
  locationTitle: "Choose your destination",
  dayTitle: "One decision before night",
  combatTitle: "The encounter",
  npUse: "Release Noble Phantasm",
  target: "Target",
  amount: "Mana to transfer",
  ownServant: "Your Servant",
  rivals: "Rival Masters",
  city: "The sleeping city",
  telemetry: "Telemetry",
  offline: "PLAYABLE OFFLINE",
  about: "A war of information, hidden destinations and simultaneous battles.",
  setup: "Configure match",
  download: "Export replay",
  SUMMONING: "Summoning",
  LOCATION: "Destination",
  DAY_ACTION: "Day action",
  COMBAT: "Night",
  FINISHED: "Conclusion",
  INVESTIGATE_SERVANT: "Investigate Servant",
  INVESTIGATE_MASTER: "Investigate Master",
  TRANSFER_MANA: "Transfer Mana",
  PREPARE_TERRAIN: "Prepare terrain",
  HIDE: "Hide",
  USE_LEYLINE: "Use leyline",
};
export function translate(locale: Locale, key: string) {
  return (locale === "en-US" ? en[key] : undefined) ?? pt[key] ?? key;
}
/** Chaves em português sem tradução inglesa; usado nos testes para evitar regressões. */
export function untranslatedKeys() {
  return Object.keys(pt).filter((key) => !Object.hasOwn(en, key));
}
